trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
#  masterConfig:
#    acceleratorConfig:
#      count: 1
#      type: NVIDIA_TESLA_V100
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: final_metric_result
    maxTrials: 6
    maxParallelTrials: 5
    params:
      - parameterName: num_timesteps
        type: INTEGER
        minValue: 3
        maxValue: 6
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: encoded_size
        type: INTEGER
        minValue: 4
        maxValue: 64
        scaleType: UNIT_LOG_SCALE

      - parameterName: batch_size
        type: INTEGER
        minValue: 64
        maxValue: 256
        scaleType: UNIT_LOG_SCALE

      - parameterName: learning_rate
        type: DOUBLE
        minValue: .0001
        maxValue: .01
        scaleType: UNIT_LOG_SCALE

      - parameterName: reg_amount
        type: DOUBLE
        minValue: .0000001
        maxValue: .001
        scaleType: UNIT_LOG_SCALE

      - parameterName: use_residual
        type: INTEGER
        minValue: 0
        maxValue: 1
        scaleType: UNIT_LINEAR_SCALE
