# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  masterConfig:
    acceleratorConfig:
      count: 1
      type: NVIDIA_TESLA_P100
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: final_metric_result
    maxTrials: 20
    maxParallelTrials: 5
    params:
      - parameterName: task
        type: CATEGORICAL
        categoricalValues: ['grid']

      - parameterName: grid_size
        type: INTEGER
        minValue: 2
        maxValue: 2
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: game_timesteps
        type: INTEGER
        minValue: 2
        maxValue: 2
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: model_timesteps
        type: INTEGER
        minValue: 2
        maxValue: 2
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: dec_enc_loss_amount
        type: DOUBLE
        minValue: 0.001
        maxValue: 0.004
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: board_size
        type: INTEGER
        minValue: 10
        maxValue: 10
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: use_task_autoencoder
        type: INTEGER
        minValue: 1
        maxValue: 1
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: encoder_layers
        type: INTEGER
        minValue: 2
        maxValue: 3
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: timestep_layers
        type: INTEGER
        minValue: 5
        maxValue: 6
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: decoder_layers
        type: INTEGER
        minValue: 1
        maxValue: 3
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: encoded_size
        type: INTEGER
        minValue: 24
        maxValue: 40
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: batch_size
        type: INTEGER
        minValue: 200
        maxValue: 512
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: learning_rate
        type: DOUBLE
        minValue: .0005
        maxValue: .00075
        scaleType: UNIT_LOG_SCALE

      - parameterName: lr_decay_rate_per1M_steps
        type: DOUBLE
        minValue: .4
        maxValue: .7
        scaleType: UNIT_LOG_SCALE

      - parameterName: reg_amount
        type: DOUBLE
        minValue: 0.0
        maxValue: 0.0
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: use_residual
        type: INTEGER
        minValue: 1
        maxValue: 1
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: eval_interval
        type: INTEGER
        minValue: 5000
        maxValue: 5000
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: max_train_steps
        type: INTEGER
        minValue: 200000
        maxValue: 200000
        scaleType: UNIT_LINEAR_SCALE
